config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  resource :profile, only: [:edit, :update, :destroy] do
    resource :gallery, only: [:show]
  end
  get :creators, to: "pages#creators"
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  validate :file_format

  private

  def file_format
    return unless file.attached?

    if !file.content_type.in?(%w(image/jpeg image/png))
      errors.add(:file, "doit être au format JPG ou PNG")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy

  devise :database_authenticatable, :rememberable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.uid + "@tyriens.fr"
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
  def show
    @images = current_user.images.order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def creators
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
  end

  def update
    if current_user.update(profile_params)
      redirect_to edit_profile_path
    else
      redirect_to edit_profile_path
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end

  private

  def profile_params
    params.require(:user).permit(:twitch_url, :youtube_url)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def discord
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Discord") if is_navigational_format?
    else
      session["devise.discord_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url, alert: request.env["omniauth.auth"]
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to root_path
  end

  # POST /resource/sign_in
  def create
    redirect_to root_path
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<header id="site-header" class="text-white absolute inset-x-0 z-20 bg-accent">
  <div class="container">
    <nav class="flex min-h-[64px] items-center justify-between py-1 lg:min-h-[90px] lg:py-4">
      <!-- Logo -->
      <div>
        <a href="/">
          Tyriens.fr version #alpha
        </a>
      </div>
      <!-- Logo / End -->

      <!-- Navigation (Desktop) -->
      <ul class="hidden gap-x-7 xl:gap-x-10 text-sm font-bold lg:flex">
        <li class="">
          <a class="relative inline-flex items-center gap-x-2 leading-10 after:absolute after:bottom-[7px] after:left-0 after:h-[2px] after:bg-white after:transition-transform after:w-full after:origin-left after:scale-x-100" href="/">
            Accueil
          </a>
        </li>
        <li class="">
          <a class="relative inline-flex items-center gap-x-2 leading-10 after:absolute after:bottom-[7px] after:left-0 after:h-[2px] after:bg-white after:transition-transform after:w-full after:origin-left after:scale-x-100" href="/creators">
            Créateurs
          </a>
        </li>
        <li class="">
          <a class="relative inline-flex items-center gap-x-2 leading-10 after:absolute after:bottom-[7px] after:left-0 after:h-[2px] after:bg-white after:transition-transform after:w-full after:origin-right hover:after:origin-left after:scale-x-0 hover:after:scale-x-100" href="#">
            Galerie (prochainement)
          </a>
        </li>
      </ul>
      <!-- Navigation (Desktop) / End -->

      <!-- Header Controls -->
      <div class="flex">

        <div class="flex items-center py-4 px-1 sm:px-2">
          <label for="theme-toggle" class="relative inline-flex cursor-pointer items-center">
            <input type="checkbox" value="" id="theme-toggle" class="peer sr-only">
            <span class="relative z-10 block h-6 w-11 rounded-full border-2 border-white after:absolute after:top-0.5 after:left-0.5 after:h-4 after:w-4 after:rounded-full after:bg-white after:transition-transform peer-checked:after:translate-x-[20px]"></span>
            <svg role="img" class="pointer-events-none absolute left-[5px] top-1 h-4 w-4 stroke-white">
              <use xlink:href="/assets/img/yt1/sprite.svg#sun"></use>
            </svg>
            <svg role="img" class="pointer-events-none absolute right-[5px] top-1 h-4 w-4 stroke-white">
              <use xlink:href="/assets/img/yt1/sprite.svg#moon"></use>
            </svg>
          </label>
        </div>

        <div class="relative [&>.sub-menu]:lg:hover:visible [&>.sub-menu]:hover:animate-popper-pop-in [&>.sub-menu]:lg:hover:opacity-100">
          <a class="block py-4 px-2 xl:px-3" href="#">
            <svg role="img" class="h-6 w-6 fill-white">
              <use xlink:href="/assets/img/yt1/sprite.svg#user"></use>
            </svg>
          </a>

          <ul class="sub-menu invisible absolute right-full z-20 -mr-9 flex w-52 origin-top-right flex-col bg-white dark:bg-gray-800 py-5 text-sm font-bold opacity-0 shadow-2xl transition-all">
            <% if current_user %>
              <li class="px-7">
                <%= link_to "Mon Profil", edit_profile_path, class: "flex flex-row-reverse items-center justify-between py-2 text-primary dark:text-white transition-colors hover:text-accent dark:hover:text-accent" %>
              </li>
              <li class="px-7">
                <%= form_with url: destroy_user_session_path, method: :delete do |form| %>
                  <%= form.submit "Déconnexion", class: "flex flex-row-reverse items-center justify-between py-2 text-primary dark:text-white transition-colors hover:text-accent dark:hover:text-accent" %>
                <% end %>
              </li>
            <% else %>
              <li class="px-7">
                <%= form_with(url: omniauth_authorize_path(:user, :discord), method: :post) do |form| %>
                  <%= form.submit "Connexion avec Discord", class: "flex flex-row-reverse items-center justify-between py-2 text-primary dark:text-white transition-colors hover:text-accent dark:hover:text-accent" %>
                <% end %>
              </li>
            <% end %>
          </ul>

        </div>

        <button class="js-menu-toggle -mr-2 inline-flex py-4 px-2 sm:px-3 lg:hidden xl:px-4">
          <svg role="img" class="js-menu-toggle-icon-open h-6 w-6 fill-white">
            <use xlink:href="/assets/img/yt1/sprite.svg#menu"></use>
          </svg>
          <svg role="img" class="js-menu-toggle-icon-close hidden h-6 w-6 fill-white">
            <use xlink:href="/assets/img/yt1/sprite.svg#menu-close"></use>
          </svg>
        </button>

      </div>
      <!-- Header Controls / End -->

    </nav>
  </div>
</header>

app/views/application/_mobile_menu.html.erb
<!-- Mobile Menu -->
<div class="js-mobile-menu p-t-[64px] fixed left-0 top-[64px] z-50 block h-[calc(100dvh-64px)] w-full translate-x-full overflow-auto bg-white dark:bg-gray-800 py-5 text-primary dark:text-white transition-transform duration-300 lg:hidden">
  <div class="container">
    <!-- Navigation (Mobile) -->
    <ul class="text-md flex flex-col font-bold">
      <li class="flex flex-wrap items-center gap-x-4 border-b border-b-gray-200 dark:border-b-gray-200/10">
        <a class="flex-grow gap-x-1 py-4 leading-normal transition-colors hover:text-accent" href="/">
          Accueil
        </a>
      </li>
    </ul>
    <!-- Navigation (Mobile) / End -->
  </div>
</div>
<!-- Mobile Menu / End -->

app/views/galeries/show.html.erb
<section class="pt-14 pb-24 lg:pb-52 lg:pt-40">
  <div class="container">
    <div class="grid grid-cols-12 gap-y-12 md:gap-x-6 lg:gap-x-7.5 content-start">

      <aside class="col-span-full md:col-span-4">
        <div class="sticky lg:top-8 xl:top-10">
          <div class="mb-10">
            <h2 class="mb-1 text-2xl font-bold tracking-tight text-primary dark:text-white md:mb-2 md:text-2xl lg:text-3.5xl"><%= current_user.username %></h2>
            <h3 class="text-lg font-bold leading-tight tracking-tight text-accent lg:text-xl xl:text-[26px]">Bienvenue !</h3>
          </div>
          <nav class="py-1">
            <ul class="flex flex-col gap-y-4 font-bold leading-tight lg:gap-y-6 lg:text-lg">
              <li class="">
                <%= link_to "Mon Profil", edit_profile_path, class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
              </li>
              <li class="">
                <% if current_user.images.any? %>
                  <%= link_to "Ma Galerie (#{pluralize(current_user.images.count, "image")})", profile_gallery_path, class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
                <% else %>
                  <%= link_to "Ma Galerie (prochainement)", "#", class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
                <% end %>
              </li>
              <li class="mt-5">
                <%= form_with(url: profile_path, method: :delete) do |form| %>
                  <%= form.submit "Supprimer mon compte", class: "text-red-500 text-lg transition-all opacity-60 hover:opacity-100 hover:text-primary dark:hover:text-white" %>
                <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </aside>

      <div class="col-span-full md:col-span-8">
        <h2 class="mb-8 text-2xl font-bold tracking-tight text-primary dark:text-white md:text-2xl lg:mb-16 lg:text-3.5xl">Galerie <span class="text-accent"></span></h2>

        <div class="text-xl font-bold text-accent mb-8">
          Ces images proviennent de tes envois au bot Discord Tyriens et permettront de créer ta galerie : tu pourras choisir quelle image afficher à la une, quelles images publier et partager, quelles images supprimer...
        </div>

        <div class="grid grid-cols-2 gap-2">
          <% @images.each do |image| %>
            <div>
              <%= image_tag url_for(image.file), class: "h-auto max-w-full rounded-lg" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr" class="h-full overflow-x-hidden">
  <head>
    <title>Tyriens.fr</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="/assets/vendors/common/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/vendors/common/swiper/css/swiper-bundle.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="antialiased tracking-tight font-base text-gray-500 text-base h-full bg-white dark:bg-gray-900 overflow-x-hidden">
    <div id="site-wrapper" class="flex flex-col h-full js-site-wrapper">
      <div class="header-wrapper bg-accent text-white relative z-30">
        <%= render "header" %>
        <%= yield :hero %>
      </div>
      <%= render "mobile_menu" %>
      <main id="main-content" class="grow lg:pt-0">
        <%= yield %>
      </main>
      <%= render "footer" %>
    </div>

    <script src="/assets/vendors/common/glightbox/js/glightbox.min.js"></script>
    <script src="/assets/vendors/common/swiper/js/swiper-bundle.min.js"></script>
    <script src="/assets/js/common.js"></script>
    <script src="/assets/js/yt1/init.js"></script>
  </body>
</html>

app/views/pages/creators.html.erb
<section class="pt-14 pb-24 lg:pb-52 lg:pt-40">
  <div class="container">
    <div class="mb-10 grid grid-cols-12 gap-y-5 md:gap-x-[30px] lg:mb-40">
      <h2 class="col-span-full text-2xl font-bold leading-none tracking-tighter text-primary dark:text-white md:col-span-5 lg:text-4xl xl:text-5xl">Créateurs Tyriens</h2>
      <div class="col-span-full place-self-end md:col-span-7 md:col-start-7 md:col-end-13 lg:pl-[70px] lg:text-lg">
        <p class="dark:text-white">
          <% if current_user %>
            Un exemple avec Historien Atis !
          <% end %>
        </p>
      </div>
    </div>

    <% if current_user %>
      <div class="flex flex-col gap-y-5 lg:gap-y-10">
        <div class="group relative grid grid-cols-12 gap-y-4 px-7 py-7 shadow-gray-900 transition-all hover:bg-white hover:shadow-3xl dark:hover:bg-gray-800 md:px-0 lg:py-14">
          <figure class="col-span-full flex items-center justify-center p-4 md:col-span-4 md:p-0">
            <%= image_tag "historien-atis.png", class: "block h-auto max-w-full opacity-50 grayscale transition-all group-hover:opacity-100 group-hover:grayscale-0 w-40" %>
          </figure>
          <div class="col-span-full leading-relaxed md:col-span-7">
            <div class="mb-6 dark:text-white">Conteur d'histoire sur Guild Wars</div>
            <a class="text-sm font-bold text-primary transition-colors after:absolute after:inset-0 hover:text-accent dark:text-white dark:hover:text-accent" href="https://youtube.com/c/HistorienAtis" target="_blank">YouTube</a>
          </div>
        </div>
      </div>
    <% end %>

    <div class="h-24 md:h-32 lg:h-52"></div>

    <div class="grid grid-cols-12 text-center">
      <div class="col-span-full sm:col-start-3 sm:col-end-11 md:col-start-2 md:col-end-12 lg:col-start-3 lg:col-end-11">
        <div class="mb-2 text-xl leading-normal text-primary dark:text-white md:text-2xl"></div>
        <h3 class="text-2xl font-bold leading-tight tracking-tighter text-primary dark:text-white md:text-4xl md:leading-none lg:text-[42px] xl:text-5xl">
          Tes créations sur Tyriens.fr&nbsp;?<br>
          <a class="text-accent transition-opacity hover:opacity-80" href="https://discord.gg/t8FWtnBUqS">Parlons-en</a>
          sur Discord, envoie un message à Arka#6594 ou...
          <%= form_with(url: omniauth_authorize_path(:user, :discord), method: :post) do |form| %>
            <%= form.submit "Connecte-toi avec Discord !", class: "text-accent transition-opacity hover:opacity-80" %>
          <% end %>
        </h3>
      </div>
    </div>
  </div>
</section>

app/views/profiles/edit.html.erb
<section class="pt-14 pb-24 lg:pb-52 lg:pt-40">
  <div class="container">
    <div class="grid grid-cols-12 gap-y-12 md:gap-x-6 lg:gap-x-7.5 content-start">

      <aside class="col-span-full md:col-span-4">
        <div class="sticky lg:top-8 xl:top-10">
          <div class="mb-10">
            <h2 class="mb-1 text-2xl font-bold tracking-tight text-primary dark:text-white md:mb-2 md:text-2xl lg:text-3.5xl"><%= current_user.username %></h2>
            <h3 class="text-lg font-bold leading-tight tracking-tight text-accent lg:text-xl xl:text-[26px]">Bienvenue !</h3>
          </div>
          <nav class="py-1">
            <ul class="flex flex-col gap-y-4 font-bold leading-tight lg:gap-y-6 lg:text-lg">
              <li class="">
                <%= link_to "Mon Profil", edit_profile_path, class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
              </li>
              <li class="">
                <% if current_user.images.any? %>
                  <%= link_to "Ma Galerie (#{pluralize(current_user.images.count, "image")})", profile_gallery_path, class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
                <% else %>
                  <%= link_to "Ma Galerie (prochainement)", "#", class: "text-lg transition-all text-primary opacity-100 hover:text-accent dark:text-white dark:hover:text-accent" %>
                <% end %>
              </li>
              <li class="mt-5">
                <%= form_with(url: profile_path, method: :delete) do |form| %>
                  <%= form.submit "Supprimer mon compte", class: "text-red-500 text-lg transition-all opacity-60 hover:opacity-100 hover:text-primary dark:hover:text-white" %>
                <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </aside>

      <div class="col-span-full md:col-span-8">
        <h2 class="mb-8 text-2xl font-bold tracking-tight text-primary dark:text-white md:text-2xl lg:mb-16 lg:text-3.5xl">Informations de ton profil <span class="text-accent"></span></h2>
        <div>

          <div class="text-xl font-bold text-accent mb-8">
            Ces informations permettront d'afficher un lien vers tes réseaux sur ta galerie.
          </div>

          <%= form_with(model: current_user, url: profile_path, method: :put, class: "grid grid-cols-6 gap-x-7 gap-y-7 md:gap-x-7 lg:gap-x-[30px]") do |form| %>
            <div class="col-span-full md:col-span-3">
              <%= form.label :youtube_url, "YouTube", class: "dark:text-white" %>
              <%= form.url_field :youtube_url, class: "group-[.is-success]:bg-input-success group-[.is-error]:border-danger group-[.is-error]:bg-input-invalid group-[.is-error]:text-danger group-[.is-success]:pr-16 group-[.is-invalid]:pr-16 border-base bg-[length:14px_14px,_46px_46px] bg-[position:right_26px_center,_right_10px_center] bg-no-repeat font-bold leading-8 tracking-tight text-primary transition-all duration-150 placeholder:font-normal placeholder:text-gray-500/60 focus:border-indigo-500 focus:outline-0 focus:ring-0 dark:border-white/10 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500/80 dark:focus:border-indigo-500 w-full px-7 py-4", placeholder: "URL de ton compte YouTube" %>
              <p class="group-[.is-error]:block mt-2 hidden text-sm font-bold text-danger">

              </p>
            </div>
            <div class="col-span-full md:col-span-3">
              <%= form.label :twitch_url, "Twitch", class: "dark:text-white" %>
              <%= form.url_field :twitch_url, class: "group-[.is-success]:bg-input-success group-[.is-error]:border-danger group-[.is-error]:bg-input-invalid group-[.is-error]:text-danger group-[.is-success]:pr-16 group-[.is-invalid]:pr-16 border-base bg-[length:14px_14px,_46px_46px] bg-[position:right_26px_center,_right_10px_center] bg-no-repeat font-bold leading-8 tracking-tight text-primary transition-all duration-150 placeholder:font-normal placeholder:text-gray-500/60 focus:border-indigo-500 focus:outline-0 focus:ring-0 dark:border-white/10 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500/80 dark:focus:border-indigo-500 w-full px-7 py-4", placeholder: "URL de ton compte Twitch" %>
              <p class="group-[.is-error]:block mt-2 hidden text-sm font-bold text-danger">

              </p>
            </div>
            <div class="col-span-full pt-8">
              <%= form.submit "Enregistrer", class: "block w-full bg-accent py-5 text-lg font-bold leading-normal tracking-tight text-white transition-colors hover:cursor-pointer hover:bg-accent/90" %>
            </div>
        <% end %>



        </div>
      </div>

    </div>
  </div>
</section>